/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_AD6CC46__
#define __PLUGINEDITOR_H_AD6CC46__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "ClickableLabel.h"


class JuceBoxAudioProcessorEditor :
	public AudioProcessorEditor, public Timer,
	public ClickableLabel::ClickListener
{
public:
    JuceBoxAudioProcessorEditor (JuceBoxAudioProcessor* ownerFilter);
    ~JuceBoxAudioProcessorEditor();

    void	paint(Graphics& g);
		void	resized();
		void	labelClicked(Label* clickedLabel);
		void	timerCallback();

protected:
		ClickableLabel	fileLabel;
		Label 	pathLabel;
		Label 	infoLabel;
		MidiKeyboardComponent	midiKeyboard;

		JuceBoxAudioProcessor* getProcessor() const {
			return static_cast<JuceBoxAudioProcessor*> (getAudioProcessor());
			}

		void	chooseFile();
		void	setFile(File* newFile);
		void	updateFile(File* file);
};


#endif  // __PLUGINEDITOR_H_AD6CC46__
